spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_SQL}:5432/${DB_NAME}
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  mongodb:
    uri: mongodb://${DB_HOST_NOSQL}:27017/${DB_NAME}

